apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: demo-apps
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
        location /api/ {
            # Proxy to local Envoy sidecar which establishes mTLS to backend
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location /realms/ {
            # Proxy to Keycloak
            proxy_pass http://keycloak.zero-trust-infra.svc.cluster.local:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
