apiVersion: v1
kind: Pod
metadata:
  name: backend-test
  namespace: demo-apps
spec:
  serviceAccountName: backend-service
  containers:
  - name: app
    image: alpine:3.19
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /run/spire/sockets
      readOnly: true
  volumes:
  - name: spire-agent-socket
    csi:
      driver: "csi.spiffe.io"
      readOnly: true
