apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-webhook-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: webhook-server
    protocol: TCP
    name: webhook-server
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller
