apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: ${KEYCLOAK_NAMESPACE}
  labels:
    app.kubernetes.io/name: keycloak
type: Opaque
stringData:
  host: "${RDS_HOST}"
  port: "${RDS_PORT}"
  database: "${RDS_DATABASE}"
  username: "${RDS_USERNAME}"
  password: "${RDS_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: ${KEYCLOAK_NAMESPACE}
  labels:
    app.kubernetes.io/name: keycloak
type: Opaque
stringData:
  admin-username: "${KEYCLOAK_ADMIN_USERNAME}"
  admin-password: "${KEYCLOAK_ADMIN_PASSWORD}"
