apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-csi-driver
  namespace: spire-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-csi-driver-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-csi-driver-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-csi-driver-cluster-role
subjects:
- kind: ServiceAccount
  name: spire-csi-driver
  namespace: spire-system
